### ISSUE TITLE
[Umbrella] Optimize time of `make setup`

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#119]
1. [Do nothing if the target base image exists](https://github.com/neuromation/cookiecutter-neuro-project/issues/115)
2. Minimize default packages in [`requirements.txt`](https://github.com/neuromation/template-base-image/issues/9) and [`apt.txt`](https://github.com/neuromation/template-base-image/issues/10#issuecomment-537441138)
3. Optimize `neuro cp` (https://github.com/neuromation/cookiecutter-neuro-project/issues/93, *more ideas?*)
4. [Optimize `apt-get update/install`](https://github.com/neuromation/template-base-image/issues/11)
5. Optimize `neuro run` (~pre-load base image on nodes: done~)
6. Optimize `neuro save`:
6.1 ~pre-load base image on nodes: done~,
6.2 minimize the size of image (we already do `rm -rf /var/lib/apt/lists/*`, maybe we can cleanup the image more, assuming that there will be no more packages installed)

**Comment by YevheniiSemendiak** [comment]
outdated, we changed both build process and base image itself
