### ISSUE TITLE
Tests: improve test re-run strategy

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#142]
In PR https://github.com/neuromation/cookiecutter-neuro-project/pull/127, we refused to use pytest's option `--retry` and set up support for test re-run in the test runners (`helpers/runners.py`). 

It'll be better if we could specify on which exactly error patterns the test should retry (or vice versa: on which error patterns it should NOT retry).

**Comment by YevheniiSemendiak** [comment]
outdated
