### ISSUE TITLE
Add more checks to tests

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#154]
1. tests that use `_test_make_run_something_useful` (`jupyter`, `filebrowser`, `tensorboard`):
1.1 check directories mounted (now absent)
2. ~add tests on `make training` (now absent)~
3. ~add tests on SSH server availability for `make training` (via neuro port-forward, which is missing now)~

**Comment by YevheniiSemendiak** [comment]
those tests are performed manually when something related is changed.
or if its a change in action - action is tested
if the change in base image - base image is tested.

testing here end-to-end the project generation and action implementation is too expencive
