### ISSUE TITLE
`make setup` mounts project root as read-only

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#171]
https://github.com/neuromation/cookiecutter-neuro-project/blob/06aee7e4a384ea1d481b80f738331f97b2de10f6/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L68

So: either we don't need this mount, or, if we do write there, it should mount as `rw`

**Comment by mariyadavydova** [comment]
Why is this a problem?
This mount is used for reading files with pip and apt requirements. AFAIU, you don't need to update these files or the content of this folder while performing set up, but you need to read these files. Is it correct?

**Comment by YevheniiSemendiak** [comment]
outdated
