### ISSUE TITLE
Shorten env var `PROJECT_POSTFIX`

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#177]
https://github.com/neuromation/cookiecutter-neuro-project/blob/780d1aa8f174b7f786e0561ef2c8af2c4decc558/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L16 

`PROJECT_POSTFIX` -> `PROJECT` (it's project name, not just postfix)

**Comment by ayushkovskiy** [comment]
+ reuse it in other env vars of the Makefile:
`PROJECT_PATH_STORAGE`, `PROJECT_PATH_ENV`, ...

I.e. there should be only 1 line `{{cookiecutter.project_slug}}` in Makefile.

**Comment by ayushkovskiy** [comment]
+ fix variables in tests: https://github.com/neuromation/cookiecutter-neuro-project/blob/master/tests/e2e/configuration.py

**Comment by YevheniiSemendiak** [comment]
outdated
