### ISSUE TITLE
Add real paths to `make help`

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#18]
Example: 
`upload_code                    Upload code directory to Storage`
will better look like
`upload_code                    Upload code directory: `/home/artem/project/modules` -> `storage://artem/project/modules`

But it's complicated to do so with current `make help` approach as `make` as the variables are encoded into env vars, that are expanded by make itself, but the comments are written as make comments.

**Comment by YevheniiSemendiak** [comment]
outdated
