### ISSUE TITLE
Maybe we should consider moving test runners from pexpect to subprocess

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#187]
See arguments here: https://github.com/neuromation/cookiecutter-neuro-project/issues/162#issuecomment-558723802

**Comment by ayushkovskiy** [comment]
Note: test failed because the output (returned by `run()`) was incomplete, see https://circleci.com/gh/neuromation/cookiecutter-neuro-project/1279

**Comment by YevheniiSemendiak** [comment]
outdated
