### ISSUE TITLE
Flaky test: sometimes `gsutil` is not authorized with `make jupyter`

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#257]
see https://circleci.com/gh/neuromation/cookiecutter-neuro-project/1515. Encountered only once in hourly-run test suite in period Dec 13 - Dec 16, 2019.

**Comment by ayushkovskiy** [comment]
Perhaps related: `wandb` auth failed. Also a rare catch.
https://circleci.com/gh/neuromation/cookiecutter-neuro-project/1550

I think, the first step to debug this problem should be to add more assertions on auth file existence (in case if it's an NFS mount glitch) + on presence of `wandb` pip package

**Comment by ayushkovskiy** [comment]
very rare catch, not critical currently. We'll return to it later if we ensure this problem again.

**Comment by YevheniiSemendiak** [comment]
outdated
