### ISSUE TITLE
Move user's configuration to a separate Makefile

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#262]
In order to avoid Git conflicts between existing complicated targets of current Makefile and the custom user's code while Template upgrade. 

Plus, change the documentation to teach users not to edit the "our" Makefile but only "theirs".

```
--
"their" Makefile: `Makefile`
--
include neuro.mk

DATA_DIR?=data
CONFIG_DIR?=config
CODE_DIR?={{cookiecutter.code_directory}}
NOTEBOOKS_DIR?=notebooks
RESULTS_DIR?=results
...
```

```
--
"our" Makefile: `neuro.mk`
--

##### COMMANDS #####

APT?=apt-get -qq
PIP?=pip install --progress-bar=off -U --no-cache-dir
NEURO?=neuro

ifeq (${TRAIN_STREAM_LOGS}, yes)
	TRAIN_WAIT_START_OPTION=--wait-start --detach
else
	TRAIN_WAIT_START_OPTION=
endif
...
```

**Comment by ayushkovskiy** [comment]
not urgent for `Jan2020` iteration.

**Comment by ayushkovskiy** [comment]
Need to find a way to ignore this custom user's Makefile while upgrading the Template (so that user's changes are not overwritten).

**Comment by YevheniiSemendiak** [comment]
outdated
