### ISSUE TITLE
Improve train.py

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#269]
As a continuation of https://github.com/neuromation/cookiecutter-neuro-project/issues/265, improve train.py: add a small argparser 
https://github.com/neuromation/ml-recipe-hier-attention/blob/965f9129c587331cb40051a40d429f6eec432e56/src/train_catalyst.py#L64-L72

**Comment by ayushkovskiy** [comment]
also add a constants.py:
https://github.com/neuromation/ml-recipe-hier-attention/blob/master/src/const.py

**Comment by ayushkovskiy** [comment]
not urgent for `Jan2020` iteration.

**Comment by ayushkovskiy** [comment]
not urgent for `Jan2020` iteration.

**Comment by YevheniiSemendiak** [comment]
Is it still actual?

**Comment by YevheniiSemendiak** [comment]
outdated
