### ISSUE TITLE
Develop job is terminated after OOM error during debug in console

### ISSUE THREAD

**Issue by atselousov** [neuro-inc/cookiecutter-neuro-project#321]
After connection to a develop job with `neuro exec bash` to debug code, execution of any code, which raises OOM error, also causes a termination of a job.

**Comment by ayushkovskiy** [comment]
ehh, this is the problem of the Platform, not Template. Currenlty, we don't have strategy of what to do in case of OOM

**Comment by yartem** [comment]
We could implement a script (bash, using `free`) that checks memory consumption in background, and if memory exceeded by a threshold (95%), it'll send a signal that python code can handle gracefully.

**Comment by YevheniiSemendiak** [comment]
implemented OOM-Guard in the base image.
