### ISSUE TITLE
Custom code import does not always work

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#358]
https://github.com/neuromation/cookiecutter-neuro-project/blob/03d78fac4fabd59afe7017b24ab642f06beb9ed5/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L317

this does not work when run from Web Shell. Need more general case where the code is imported right in Jupyter Notebook -- for example `sys.path.append("..")`

**Comment by YevheniiSemendiak** [comment]
outdated
