### ISSUE TITLE
Add target to connect to `train`

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#364]
`tail -f /output` sometimes gets disconnected due to network or whatever. It's better to add a target to re-connect.

**Comment by YevheniiSemendiak** [comment]
It's actually not a project template problem, but a platform client problem. Was fixed (hopefully)in [this](https://github.com/neuro-inc/platform-client-python/blob/master/CHANGELOG.md#neuro-sdkcli-21216-2021-02-16) release
