### ISSUE TITLE
Provide a target to build docker image to use outside the Platform

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#385]
See comment https://github.com/neuromation/ml-recipe-project-zero/pull/1#discussion_r405416445 and onward.

Would be great to change `make setup` to the following:
- Have a Dockerfile generated by cookiecutter, something like:
```
FROM neuromation/base
COPY requirements.txt /project/
COPY startup.sh /project/
COPY build.sh /project/
RUN sh /project/bulid.sh

EXPOSE 8888
```
- Have an empty shell script `build.sh` that's executed as a step in Dockerfile

The only problem here is how to build this image on the platform -- so far we don't have API for that.

**Comment by yartem** [comment]
So this Dockerfile could be great for better control (more clear what environment you use) , reproducibility and portability (can give Dockerfile to the client and use it anywhere).

**Comment by YevheniiSemendiak** [comment]
we do rely on a dockerfiles now
users could build them locally
or pull images from the platform
the issue is outdated
