### ISSUE TITLE
Set up tests against master branch neuro CLI

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#401]
What tests we want to have:
- `cookiecutter-neuro-project` release + `neuro` release
- `cookiecutter-neuro-project` master + `neuro` release
- `cookiecutter-neuro-project` release + `neuro` master

**Comment by YevheniiSemendiak** [comment]
the intent is not clear
not why we need to release cookiecutter with the master version of neuro-cli.

in the end, the Cookiecutter is used a plug-in into the CLI, so I guess there is no need to add such backward dependency.
