### ISSUE TITLE
Extract tests into a separate package

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#422]
- new package `cookiecutter-neuro-project-tests` should contain test functions to be used from python, something like:
```
>>> from cookiecutter_neuro_project_tests.test_runners import test_live_yml_valid, get_all_jobs, test_job
>>> test_live_yml_valid(path_to_live_yml)
>>> for job in path_to_live_yml(path_to_live_yml):
>>>      test_job(job)
```
- in addition, the tests should be declared as pytest-compatible functions in order to be imported and run against a custom project from CLI (yet not sure how exactly)
- tests in the new package `cookiecutter-neuro-project-tests` should be validated against a hard-coded working version of `cookiecutter-neuro-project` stored inside `cookiecutter-neuro-project-tests` project.
- each branch and PR of `cookiecutter-neuro-project` should pip-install a stable version of `cookiecutter-neuro-project-tests` and run test suite. 

As a result, we get:
1. No need to release Cookiecutter just to fix tests on `release` branch
2. Any other neuro-flow-derived project can use these tests natively as a pip package

**Comment by YevheniiSemendiak** [comment]
not actual, we're not generating NF description files programmatically (yet)
if we will do - this will be the part of NF repository
