### ISSUE TITLE
Cleanup test images

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#426]
1. https://github.com/neuro-inc/neuro-extras/blob/e866bf9733659315f0f36c787f527de1ebb443b3/.github/workflows/ci.yaml#L158-L183
2. tests like `test_image_build_custom_preset` should do `try..finally` to delete created images. Similar to clreanup scheme we have for `disk:`.

**Comment by asvetlov** [comment]
Try/except is fine but not enough. A canceled job can be stopped at arbitrary point. You need to search for resources created by tests and long living for more than a day, and kill them.

**Comment by YevheniiSemendiak** [comment]
wrong repo, in NE we fixed that
