### ISSUE TITLE
Solution to the mis-branding problem

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#5]
Problem: project template with `make` commands are to be used by the very beginners, who will type `make run` instead of `neuro run`. Since for the first time we can not get rid of `make` (can we?), let's prefix all `Makefile` targets with `neuro-`:
`make neuro-setup`
`make neuro-upload-code`
`make neuro-run-training`

so that our users don't forget that they work with Neuromation Platform :smile:

**Comment by YevheniiSemendiak** [comment]
outdated, we migrated to NF
