### ISSUE TITLE
Think about `data` folder

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/cookiecutter-neuro-project#79]
It is said that ML engineers hardly ever have data and code in the same place. Code usually goes on SSD, while data is stored on slow drives and often shared between many projects.

We should think about this folder usage.

**Comment by anayden** [comment]
We don't have to ask them to copy/move files to the folder. Perhaps we should educate them how to symlink their folder to `data/`. What do you think?

**Comment by YevheniiSemendiak** [comment]
outdated I think, the majority does use the `data` folder without such complains
